# This is a basic workflow to help you get started with Actions

name: Use artifact

# Controls when the workflow will run
on:
  pull_request:
    types: [closed]
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: file
          run-id: ${{ github.event.workflow_run.id }}
          branch: beta
          
          
      - uses: actions/upload-artifact@v3
        with:
          name: used_file
          path: ./downloaded.txt
